<?php


namespace App\Voters;


use App\Entity\User;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\Voter\Voter;

class BookingVoter extends Voter
{
    const BOOK = 'book';

    public function supports($attribute, $subject)
    {
        if (!in_array($attribute, [self::BOOK])) {
            return false;
        } else {
            return true;
        }
    }

    public function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        $user = $token->getUser();

        if (!$user instanceof User) {
            return false;
        }

        if (count($user->getBookings()) > 5) {
            throw new \LogicException('Vous ne pouvez pas avoir plus de 5 livres !');
        } else {
            return true;
        }
    }

    public function vote(TokenInterface $token, $subject, array $attributes)
    {
        return parent::vote($token, $subject, $attributes); // TODO: Change the autogenerated stub
    }



}